# Generated by Django 6.0.6 on 2026-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, help_text='Your course or academic program', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_interests',
            field=models.CharField(blank=True, help_text='Your target field or career interests', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe your work experience, projects, or background'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='List your skills separated by commas'),
        ),
    ]
