# Generated by Django 6.0.6 on 2026-10-07 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='career_field',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='expertise',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
